enum ActionTypes {
  DEFAULT_TYPE = "DEFAULT",
  USER_SEARCH_START = "USER_SEARCH_START",
  USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS",
  USER_SEARCH_FAIL = "USER_SEARCH_FAIL",

  USER_FOLLOWER_COUNT_START = "USER_FOLLOWER_COUNT_START",
  USER_FOLLOWER_COUNT_SUCCESS = "USER_FOLLOWER_COUNT_SUCCESS",
  USER_FOLLOWER_COUNT_FAIL = "USER_FOLLOWER_COUNT_FAIL",
}
export default ActionTypes;
