enum ActionTypes {
  // DEFAULT TYPE
  DEFAULT_TYPE = "DEFAULT",
  USER_SEARCH_START = "USER_SEARCH_START",
  USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS",
  USER_SEARCH_FAIL = "USER_SEARCH_FAIL",
}
export default ActionTypes;
