enum ActionTypes {
  DEFAULT_TYPE = "DEFAULT",
  USER_SEARCH_START = "USER_SEARCH_START",
  USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS",
  USER_SEARCH_FAIL = "USER_SEARCH_FAIL",

  REPO_SEARCH_START = "REPO_SEARCH_START",
  REPO_SEARCH_SUCCESS = "REPO_SEARCH_SUCCESS",
  REPO_SEARCH_FAIL = "REPO_SEARCH_FAIL",
}
export default ActionTypes;
